services:
  kafka:
    image: apache/kafka:4.1.2
    ports:
      - "127.0.0.1:9092:9092"

    environment:
      # Local setup mein ek node broker aur controller dono ka kaam karega
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Windows clients, Docker clients aur controller ke alag listeners
      KAFKA_LISTENERS: "EXTERNAL://:9092,INTERNAL://:19092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:9092,INTERNAL://kafka:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Sirf ek broker hai, isliye internal topics ki replication bhi 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # Topics manually create karenge aur data volume mein rakhenge
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  kafka-data: