spring.application.name=order-service
server.port = 8081

spring.datasource.url=jdbc:mysql://localhost:3306/order_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# IntelliJ se chalne wali service Windows host listener use karegi
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Order ID key ko String se bytes mein convert karega
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Event object ko JSON bytes mein convert karega
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# Leader sab current in-sync replicas ki acknowledgement ka wait karega
spring.kafka.producer.acks=all

# Event ka topic configuration se lenge
app.kafka.topics.order-placed=order-placed

# Send result ke liye maximum wait, seconds mein
app.kafka.publish-timeout-seconds=10

# Metadata ya buffer available hone ke liye send() ka maximum blocking time
spring.kafka.producer.properties[max.block.ms]=5000